<a href="https://colab.research.google.com/github/Madoulamine/Python_to_Machine_Learning/blob/notebook_6.ipynb/notebook_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jour 7 - 21 Juillet 2026 : Introduction à NumPy

Bienvenue dans la semaine Data Science ! Aujourd'hui, nous découvrons **NumPy** (Numerical Python). C'est la bibliothèque de référence pour manipuler des données numériques en Python.

## 1. Pourquoi NumPy ?
En Python classique, on utilise des listes. Mais pour faire des calculs mathématiques sur de grandes quantités de données, les listes sont lentes. NumPy introduit le **ndarray** (tableau N-dimensionnel), qui est beaucoup plus rapide et occupe moins de mémoire.

In [ ]:
import numpy as np # On importe numpy et on lui donne le surnom 'np' (une convention universelle)

# Création d'un tableau numpy à partir d'une liste
notes = np.array([12, 15, 9, 18, 11])
print(notes)
print("Type de l'objet :", type(notes))

In [1]:
import numpy as np

a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
print(a+a) # c'est la force de numpy et la differance entre numpy et Liste
print(type(a))
print("\t########################################################\n")

# Faisons la difference entre numpy et Liste
list_python = [2, 4, 6, 8]
list_numpy = np.array([2,4,6,8])

lp = list_python + list_python
ln = list_numpy + list_numpy

print(f"La somme des Listes en Python: {lp}\n")
print(f"La somme des Numpy en Python: {ln}\n")

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
<class 'numpy.ndarray'>
	########################################################

La somme des Listes en Python: [2, 4, 6, 8, 2, 4, 6, 8]

La somme des Numpy en Python: [ 4  8 12 16]



## 2. Dimensions et Formes (Shape)
Un tableau NumPy peut avoir 1 dimension (une ligne), 2 dimensions (une matrice avec lignes et colonnes) ou plus. La méthode `.shape` nous donne sa forme.

In [ ]:
matrice = np.array([[1, 2, 3], [4, 5, 6]])
print(matrice)
print("Forme (lignes, colonnes) :", matrice.shape)

## 3. Opérations vectorisées
La vraie magie de NumPy : on peut faire des opérations mathématiques directement sur le tableau entier sans écrire de boucle `for` !

In [ ]:
print("Notes + 2 (points bonus) :", notes + 2)
print("Notes multipliées par 2 :", notes * 2)
print("Moyenne des notes :", notes.mean())

---
## 🏆 Défi du Jour 7

1. Créez un tableau NumPy 1D appelé `temperatures` contenant les températures suivantes : 22.5, 18.0, 25.3, 19.8.
2. Affichez la forme (`shape`) de ce tableau.
3. Convertissez ces températures de Celsius en Fahrenheit en utilisant la formule vectorisée : `F = C * 9/5 + 32`.
4. Affichez la température maximale du tableau final (indice : utilisez `.max()`).

In [7]:
# Écrivez votre code pour le défi ici
#Créez un tableau Numpy temperatures contenant les values:
import numpy as np
temperatures = np.array([22.5, 18.0, 25.3, 19.8])

#affiche la forme shape de ce tableau
print(f"La forme de mon tableau est: {temperatures.shape}")
print(f"Les temperatures en C: {temperatures} C")

#convertissement de Celsius en Fahrenheit F = C * 9/5 + 32
F = (temperatures * 9/5) + 32
print(f"Les temperatures en F: {F} F")

# la temperature max de mon tableau final
print(f"La temperature max de mon tab final est: {F.max()}")


La forme de mon tableau est: (4,)
Les temperatures en C: [22.5 18.  25.3 19.8] C
Les temperatures en F: [72.5  64.4  77.54 67.64] F
La temperature max de mon tab final est: 77.54
